### ISSUE TITLE
DOI?

### ISSUE THREAD

**Issue by dguest** [iml-wg/HEP-ML-Resources#19]
Hey, it might be nice to be able to cite this in some way so that we can point people to it in more "official" documentation. I don't have strong opinions but Zenodo works ok: the only annoying thing is that you then have to create "releases" which might sort of be contrary to the idea of a living document.

**Comment by matthewfeickert** [comment]
@dguest I think that sounds like a really good idea, and in line with what Kyle was discussing with us at Hammers and Nails 2017. 

You're just thinking that we would just use Git to tag the repo at different stages? Would we tag the repo after each change, or would we just do this after large changes (like once per 3 months or something)? Or is [Zenodo](https://zenodo.org/) supposed to be something that is similar to commits in Git?

**Comment by dguest** [comment]
Zenodo just copies your releases, assigns them a DOI, and promises to save them ~forever. But since it's only releases I would naively just do it "on demand", i.e. after large changes or if someone wants a more up to data version.

It also gives you a DOI that points to the most recent version, which is probably more useful to most people.

**Comment by matthewfeickert** [comment]
@dguest So I don't have Owner permissions of the project (just Member) permissions, so I think I'm going to need to follow up with @omazapa and @SergeiML on how to get this working. Currently when I login to Zenodo I don't have permissions for "[approving OAuth Apps for your organization](https://help.github.com/articles/approving-oauth-apps-for-your-organization/)".

@omazapa and @SergeiML, I'll bug you on email as well, but can you either give me the relevant permissions or can you set this up?

Sorry for the late follow up, Dan.

**Comment by matthewfeickert** [comment]
We have Zenodo DOI generation now with commit a89e462954ead90606e0f7df235948e657476cdc! 

[![DOI](https://zenodo.org/badge/89476450.svg)](https://zenodo.org/badge/latestdoi/89476450)

Thanks for the great idea, @dguest. I'll close this issue now.
