### ISSUE TITLE
Add dataset section

### ISSUE THREAD

**Issue by mickypaganini** [iml-wg/HEP-ML-Resources#26]
It could be useful to add links to open datasets, such as the ones on CERN Opendata, Zenodo, UCI ML-Physics, etc.

**Comment by matthewfeickert** [comment]
@mickypaganini Sure. Do you have particular datasets in mind? Or just linking to the sites?

The [MLPhysics Portal](http://mlphysics.ics.uci.edu/) is easy to find and it is clear what is available from that, but for [CERN Opendata](http://opendata.cern.ch/search?page=1&size=20&type=Dataset) and [Zenodo](https://zenodo.org/search?page=1&size=20&q=&type=dataset&access_right=open) there is a huge amount there, so is it helpful to add some starting search filters?

**Comment by matthewfeickert** [comment]
@mickypaganini I know you're busy writing your thesis, but if I can ping you again on this it would be great to get your feedback. The idea sounds like an important one so it would be nice to incorporate.

**Comment by matthewfeickert** [comment]
@mickypaganini I think that the [CERN IML page on public datasets](https://iml.web.cern.ch/public-datasets) essentially provides this, so I think I'll just add a section that links to that now.

Let me know your thoughts and if you think we could improve on this, or on the existing resource.
