### ISSUE TITLE
Add EMD for Rare Phenomena at Colliders

### ISSUE THREAD

**Issue by nfcastro** [iml-wg/HEP-ML-Resources#74]
Dear all,

Would it be possible to add our preprint to the IML paper list?
https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=find%20eprint%202004.09360

Thanks a lot,
Nuno

**Comment by matthewfeickert** [comment]
> Would it be possible to add our preprint to the IML paper list?

Sure, though I won't get to it until tomorrow. It will be faster for you to just open a PR.

**Comment by nfcastro** [comment]
Thanks a lot. I'm happy to do what is needed - but what you like me to do? Not sure what is the policy for doing a pull request here...

**Comment by matthewfeickert** [comment]
There are instructions in CONTRIBUTING.md: https://github.com/iml-wg/HEP-ML-Resources/blob/master/CONTRIBUTING.md#how-do-i-add-a-paper

**Comment by nfcastro** [comment]
thanks.

PR done: https://github.com/iml-wg/HEP-ML-Resources/pull/75
